# Generated by Django 2.1.2 on 2018-11-14 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_student_year'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Laboratory', 'LABORATORY'), ('Seminary', 'SEMINARY'), ('Lecture', 'LECTURE')], editable=False, max_length=10, verbose_name='The different possible values for a meeting')),
                ('attendenceRequired', models.BooleanField(default=False, verbose_name='Is attendence mandatory?')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='subject.Subject', verbose_name='This meeting is a meeting for the subject..')),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekNumber', models.SmallIntegerField(choices=[(0, 'Week 0'), (1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4'), (5, 'Week 5'), (6, 'Week 6'), (7, 'Week 7'), (8, 'Week 8'), (9, 'Week 9'), (10, 'Week 10'), (11, 'Week 11'), (12, 'Week 12'), (13, 'Week 13'), (14, 'Week 14')], null=True)),
                ('isPresent', models.BooleanField(null=True)),
                ('grade', models.BooleanField(null=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='meeting.Meeting')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.Student')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.Teacher')),
            ],
        ),
    ]
