# Generated by Django 2.1.3 on 2018-12-06 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('laboratory', 'Laboratory'), ('seminary', 'Seminary'), ('lecture', 'Lecture')], editable=False, max_length=10, verbose_name='meeting_type')),
                ('attendance_required', models.BooleanField(default=False, verbose_name='meeting_attendance_required')),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.SmallIntegerField(choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4'), (5, 'Week 5'), (6, 'Week 6'), (7, 'Week 7'), (8, 'Week 8'), (9, 'Week 9'), (10, 'Week 10'), (11, 'Week 11'), (12, 'Week 12'), (13, 'Week 13'), (14, 'Week 14')], null=True)),
                ('is_present', models.BooleanField(default=False)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.Meeting')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='subject_name')),
                ('is_optional', models.CharField(choices=[('compulsory', 'compulsory'), ('optional', 'optional'), ('another_compulsory_discipline', 'another_compulsory_discipline'), ('facultative', 'facultative'), ('failure_compulsory', 'failure_compulsory'), ('failure_optional', 'failure_optional'), ('failure_facultative', 'failure_facultative'), ('discipline_in_advance', 'discipline_in_advance')], default='compulsory', editable=False, max_length=64, verbose_name='subject_is_optional')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.Teacher', verbose_name='subject_teacher'),
        ),
        migrations.AddField(
            model_name='situation',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.Teacher'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.Subject', verbose_name='meeting_subject'),
        ),
    ]
