# Generated by Django 2.1.2 on 2018-11-14 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_student_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=150, verbose_name='Course name')),
                ('isOptional', models.BooleanField(db_column='is_optional', default=False, editable=False, null=True, verbose_name='Course optionality')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.Teacher', verbose_name='The boss of za subject')),
            ],
        ),
    ]
